# Site settings
name: 小李的博客
email: acmer_li@126.com
author: Leo Li
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/xiaoli000/blog/
baseurl: "/blog"
description: Actually, less is more!
meta_description: 小李;个人博客
motto: One only can learn by teaching.
banner: 学而不思则罔，思而不学则殆。
gems: [jekyll-paginate]
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10


exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xiaoli000
highlighter: rouge

# Build settings
#highlighter: pygments
markdown: kramdown
kramdown:
  input:         GFM
  auto_ids:      true
  syntax_highlighter: rouge
#  auto_id_prefix:'id-'
#highlighter: pygments
#markdown: redcarpet
#redcarpet:
#  extensions:
#    - fenced_code_blocks
#    - no_intra_emphasis
#    - strikethrough
#    - autolink
#    - tables

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : xiaoli000
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
